using System;
using System.Collections.Generic;
using EPiServer;
using EPiServer.Core;
using EPiServer.Filters;
using EPiServer.Security;
using EPiServer.ServiceLocation;
using ExamensuppgiftFredrik.Models;
using ExamensuppgiftFredrik.Models.Pages;
using System.Linq;
using static ExamensuppgiftFredrik.Models.NewsList;
using static ExamensuppgiftFredrik.Models.Breadcrumbs;
using EPiServer.Web.Routing;
using EPiServer.DataAbstraction;
using EPiServer.Framework.Localization;
using ExamensuppgiftFredrik.Helpers.Interfaces;
using log4net;
using ExamensuppgiftFredrik.Models.Blocks;
using ExamensuppgiftFredrik.Models.Properties;
using static Kentorse.Models.ArticlePuffsList;
using System.Web;
using EPiServer.SpecializedProperties;
using System.Web.Mvc;
using EPiServer.Web.Mvc.Html;